# Generated by Django 3.2.5 on 2021-07-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_coupons', '0002_auto_20210715_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponuser',
            name='last_used',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last used'),
        ),
    ]
