# Generated by Django 3.2.6 on 2021-10-20 16:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django_simple_coupons.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_coupons', '0003_auto_20210721_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=django_simple_coupons.models.get_applicable_to_default, size=None),
        ),
    ]
