# Generated by Django 3.2.6 on 2021-10-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_coupons', '0003_auto_20210721_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_for',
            field=models.CharField(choices=[('ALL_OBJECTS', 'All objects'), ('CONSULTATION', 'Consultation'), ('CLIENT_CONSULTATION_PACKAGE', 'Client Consultation Package')], default='ALL_OBJECTS', max_length=32),
        ),
    ]
