# Generated by Django 3.2.6 on 2021-11-18 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telehealth', '0092_customcouponsetting'),
        ('django_simple_coupons', '0004_coupon_applicable_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_to',
        ),
        migrations.AddField(
            model_name='coupon',
            name='custom_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telehealth.customcouponsetting', verbose_name='CustomSetting'),
        ),
    ]
